name: Code Check

on: push

jobs:
  code_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install mypy flake8

      - name: Do type checking (mypy)
        run: python -m mypy --strict --show-column-numbers ./

      - name: Do unit testing (unittest)
        run: python -m unittest discover -s test -p test_*.py

      - name: Do format checking (flake8)
        run: python -m flake8
